on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: "${{ matrix.config.os }} (R: ${{ matrix.config.r }}, Rust: ${{ matrix.config.rust }})"

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest, r: "release", rust: "stable-msvc" }
          - { os: windows-latest, r: "devel", rust: "stable-msvc" }
          - { os: macOS-latest, r: "release", rust: "stable" }
          - { os: ubuntu-latest, r: "release", rust: "stable" }
          - { os: ubuntu-latest, r: "devel", rust: "stable" }
          - { os: ubuntu-latest, r: "release", rust: "nightly" }

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.config.rust }}

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          rtools-version: ${{ matrix.config.rtools-version }}
          # TODO: Enable RSPM where possible
          use-public-rspm: false
          # use-public-rspm: ${{ matrix.config.r != 'devel' }}

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2

      - name: debug
        run: cat ./check/*.Rcheck/00install.out

  Coverage:
    needs: R-CMD-check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/rust
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/tarpaulin@v0.1
        with:
          args: "-- --ignore-tests --out Lcov --test-threads 1"
          version: "0.15.0"
          # out-type: Html
          # upload-to-coveralls: true
      - name: upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./lcov.info"
